### PR TITLE
Tag container image as "latest" after merge to develop

### PR DESCRIPTION
**Pull request by hluk**
Also updates base image to Fedora 36.

### CODE REVIEW

**Comment by hluk** [comment]
I've tested the new image internally in dev env.

**Review by chuazhan — APPROVED** [review]
+1

**Comment by hluk** [comment]
Oh! There was already `.github/workflows/resultsdb_frontend.yml` - different file suffix. :facepalm: 

I've updated the original file instead.

**Comment by chuazhan** [comment]
Oh. I haven't checked in the local env, I am assuming it is changed in the original file

**Pull request merged**
